/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import controller.LoginController;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.*;

/**
 *
 * @author Devandi
 */
public class FormUtama extends javax.swing.JFrame {
    
    //   memanggil variabel untuk sesi
    int id_operator = LoginController.getIdOperator();
    String nama = LoginController.getNamaOperator();
    String username = LoginController.getUserOperator();
    String password = LoginController.getPasswordOperator();
    
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        setSize(642, 443);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        timenow();
        thisday();
        
        btnLogKeluar.setText("Masuk sebagai, " + username + ".");
        btnLogKeluar.setToolTipText("Keluar sekarang, " + username);
        
        //
        FormDasbor form = new FormDasbor();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width), (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpUtama = new other.JDesktopPaneGambar();
        btnTentangKami = new javax.swing.JButton();
        btnDonatur = new javax.swing.JButton();
        btnMahasiswa = new javax.swing.JButton();
        btnDonatur1 = new javax.swing.JButton();
        btnDonatur2 = new javax.swing.JButton();
        btnDonatur3 = new javax.swing.JButton();
        btnDonatur4 = new javax.swing.JButton();
        thisday = new javax.swing.JLabel();
        timenow = new javax.swing.JLabel();
        btnLogKeluar = new javax.swing.JLabel();
        btnKeluarApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pinjam Buku Lite");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/infbuk.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        dpUtama.setBackground(new java.awt.Color(204, 204, 204));

        btnTentangKami.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnTentangKami.setForeground(new java.awt.Color(255, 255, 255));
        btnTentangKami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kembuk.png"))); // NOI18N
        btnTentangKami.setText("Tentang Kami");
        btnTentangKami.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnTentangKami.setBorder(null);
        btnTentangKami.setBorderPainted(false);
        btnTentangKami.setContentAreaFilled(false);
        btnTentangKami.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTentangKami.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTentangKami.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTentangKami.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTentangKamiMouseClicked(evt);
            }
        });

        btnDonatur.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDonatur.setForeground(new java.awt.Color(255, 255, 255));
        btnDonatur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infdon.png"))); // NOI18N
        btnDonatur.setText("Donatur");
        btnDonatur.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnDonatur.setBorder(null);
        btnDonatur.setBorderPainted(false);
        btnDonatur.setContentAreaFilled(false);
        btnDonatur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonatur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonatur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonatur.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonatur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonaturMouseClicked(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infbuk.png"))); // NOI18N
        btnMahasiswa.setText("Mahasiswa");
        btnMahasiswa.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnMahasiswa.setBorder(null);
        btnMahasiswa.setBorderPainted(false);
        btnMahasiswa.setContentAreaFilled(false);
        btnMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        btnDonatur1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDonatur1.setForeground(new java.awt.Color(255, 255, 255));
        btnDonatur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infdon.png"))); // NOI18N
        btnDonatur1.setText("Donatur");
        btnDonatur1.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnDonatur1.setBorder(null);
        btnDonatur1.setBorderPainted(false);
        btnDonatur1.setContentAreaFilled(false);
        btnDonatur1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonatur1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonatur1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonatur1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonatur1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonatur1MouseClicked(evt);
            }
        });

        btnDonatur2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDonatur2.setForeground(new java.awt.Color(255, 255, 255));
        btnDonatur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infdon.png"))); // NOI18N
        btnDonatur2.setText("Donatur");
        btnDonatur2.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnDonatur2.setBorder(null);
        btnDonatur2.setBorderPainted(false);
        btnDonatur2.setContentAreaFilled(false);
        btnDonatur2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonatur2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonatur2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonatur2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonatur2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonatur2MouseClicked(evt);
            }
        });

        btnDonatur3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDonatur3.setForeground(new java.awt.Color(255, 255, 255));
        btnDonatur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infdon.png"))); // NOI18N
        btnDonatur3.setText("Donatur");
        btnDonatur3.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnDonatur3.setBorder(null);
        btnDonatur3.setBorderPainted(false);
        btnDonatur3.setContentAreaFilled(false);
        btnDonatur3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonatur3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonatur3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonatur3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonatur3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonatur3MouseClicked(evt);
            }
        });

        btnDonatur4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDonatur4.setForeground(new java.awt.Color(255, 255, 255));
        btnDonatur4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infdon.png"))); // NOI18N
        btnDonatur4.setText("Donatur");
        btnDonatur4.setToolTipText("Tentang Pembuat Aplikasi Ini");
        btnDonatur4.setBorder(null);
        btnDonatur4.setBorderPainted(false);
        btnDonatur4.setContentAreaFilled(false);
        btnDonatur4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonatur4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonatur4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonatur4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonatur4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonatur4MouseClicked(evt);
            }
        });

        dpUtama.setLayer(btnTentangKami, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnDonatur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnMahasiswa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnDonatur1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnDonatur2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnDonatur3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpUtama.setLayer(btnDonatur4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpUtamaLayout = new javax.swing.GroupLayout(dpUtama);
        dpUtama.setLayout(dpUtamaLayout);
        dpUtamaLayout.setHorizontalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpUtamaLayout.createSequentialGroup()
                .addGroup(dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpUtamaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnTentangKami)
                        .addGap(30, 30, 30)
                        .addComponent(btnDonatur3))
                    .addGroup(dpUtamaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnDonatur)
                            .addComponent(btnDonatur1)
                            .addComponent(btnDonatur2)
                            .addComponent(btnDonatur4))))
                .addContainerGap(1036, Short.MAX_VALUE))
        );
        dpUtamaLayout.setVerticalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTentangKami)
                    .addComponent(btnDonatur3))
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnDonatur)
                .addGap(18, 18, 18)
                .addComponent(btnDonatur1)
                .addGap(18, 18, 18)
                .addComponent(btnDonatur2)
                .addGap(18, 18, 18)
                .addComponent(btnDonatur4)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        thisday.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        thisday.setText("Selasa, 66 Mei 2066");
        thisday.setToolTipText("Tanggal Sekarang");
        thisday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thisdayMouseClicked(evt);
            }
        });

        timenow.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        timenow.setText("12:34:56");
        timenow.setToolTipText("Waktu Sekarang");
        timenow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timenowMouseClicked(evt);
            }
        });

        btnLogKeluar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogKeluar.setText("Log Keluar");
        btnLogKeluar.setToolTipText("Log Keluar");
        btnLogKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogKeluarMouseClicked(evt);
            }
        });

        btnKeluarApp.setText("perpuslite Designed for notebook");
        btnKeluarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpUtama)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogKeluar)
                .addGap(191, 191, 191)
                .addComponent(btnKeluarApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addComponent(timenow)
                .addGap(18, 18, 18)
                .addComponent(thisday, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dpUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thisday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timenow)
                    .addComponent(btnLogKeluar)
                    .addComponent(btnKeluarApp))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangKamiMouseClicked
        // TODO add your handling code here:
        FormTentangKami form = new FormTentangKami();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_btnTentangKamiMouseClicked

    private void thisdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thisdayMouseClicked
        // TODO add your handling code here:
        FormWaktuTanggal form = new FormWaktuTanggal();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_thisdayMouseClicked

    private void timenowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timenowMouseClicked
        // TODO add your handling code here:
        FormWaktuTanggal form = new FormWaktuTanggal();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_timenowMouseClicked

    private void btnLogKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogKeluarMouseClicked
        // TODO add your handling code here:
        FormLogin n = new FormLogin();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogKeluarMouseClicked

    private void btnKeluarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarAppMouseClicked
        // TODO add your handling code here:
        FormUbahUser form = new FormUbahUser();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_btnKeluarAppMouseClicked

    private void btnDonaturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonaturMouseClicked
        // TODO add your handling code here:
        FormDonatur form = new FormDonatur();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_btnDonaturMouseClicked

    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMahasiswaMouseClicked
        // TODO add your handling code here:
        FormMahasiswa form = new FormMahasiswa();
        dpUtama.add(form);
        Dimension parentSize = dpUtama.getSize();
        Dimension childSize = form.getSize();
        form.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        form.setVisible(true);
    }//GEN-LAST:event_btnMahasiswaMouseClicked

    private void btnDonatur1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonatur1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonatur1MouseClicked

    private void btnDonatur2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonatur2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonatur2MouseClicked

    private void btnDonatur3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonatur3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonatur3MouseClicked

    private void btnDonatur4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonatur4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonatur4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }
    
    private void timenow() {
    // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                timenow.setText(jam + ":" + menit + ":" + detik);
            }
        };
        // Timer
        new javax.swing.Timer(1000, taskPerformer).start();
    }
    
    private void thisday() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("EEEE, dd MMMMM yyyy") ;
        thisday.setText(""+kal.format(sekarang));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonatur;
    private javax.swing.JButton btnDonatur1;
    private javax.swing.JButton btnDonatur2;
    private javax.swing.JButton btnDonatur3;
    private javax.swing.JButton btnDonatur4;
    private javax.swing.JLabel btnKeluarApp;
    private javax.swing.JLabel btnLogKeluar;
    private javax.swing.JButton btnMahasiswa;
    private javax.swing.JButton btnTentangKami;
    private javax.swing.JDesktopPane dpUtama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel thisday;
    private javax.swing.JLabel timenow;
    // End of variables declaration//GEN-END:variables
}
