/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import com.sun.glass.events.KeyEvent;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author Devandi
 */
public class FormDasbor extends javax.swing.JInternalFrame {
    
    //1. deklarasi object
    private LoginController control;
    private boolean status;
    
    //   memanggil variabel untuk sesi
    int id_operator = LoginController.getIdOperator();
    String nama = LoginController.getNamaOperator();
    String username = LoginController.getUserOperator();
    String password = LoginController.getPasswordOperator();

    /**
     * Creates new form FormDasbor
     */
    public FormDasbor() {
        initComponents();
        
        thisday();
        
        lblNamaSambut.setText("Selamat Datang, " + nama + "!");
        this.setTitle("Sambutan hangat untuk " + nama + " di Dasbor utama aplikasi.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNamaSambut = new javax.swing.JLabel();
        BtnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDesk = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Dasbor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infbuk.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNamaSambut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblNamaSambut.setForeground(new java.awt.Color(102, 102, 102));
        lblNamaSambut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaSambut.setText("Selamat Datang, Devandi");

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoapp.png"))); // NOI18N
        BtnKeluar.setBorder(null);
        BtnKeluar.setBorderPainted(false);
        BtnKeluar.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("perpuslite adalah aplikasi perpustakaan minimalis yang dikembangkan oleh Kelompok 3.");

        lblDesk.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblDesk.setForeground(new java.awt.Color(102, 102, 102));
        lblDesk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesk.setText("Bacot!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
            .addComponent(BtnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNamaSambut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNamaSambut)
                .addGap(49, 49, 49)
                .addComponent(BtnKeluar)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesk)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thisday() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("EEEE") ;
        lblDesk.setText("Semoga dihari " + kal.format(sekarang) + " ini adalah hari yang spesial untuk mu, " + nama + ". Selamat menggunakan aplikasi perpuslite ini :D");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDesk;
    private javax.swing.JLabel lblNamaSambut;
    // End of variables declaration//GEN-END:variables
}
